---
- hosts: 127.0.0.1
  connection: local
  vars_files:
    - ./vars/ssh
    - ./vars/mysql
    - ./vars/git
    - ./vars/vm
  tasks:

# ---- Clone and configure MySQL DB -------

  - name: Restore database _DialerDB.sql
    mysql_db:
      login_host: "{{mysql_address}}"
      login_user: "{{mysql_rootuser}}"
      login_password: "{{mysql_rootpassword}}"
      name: "{{mysql_dialerdb}}"
      state: import
      target: "{{path_crawlerinitandconfig}}/DBdumps/_DialerDB.sql"

  - name: Restore database _AsteriskConf.sql
    mysql_db:
      login_host: "{{mysql_address}}"
      login_user: "{{mysql_rootuser}}"
      login_password: "{{mysql_rootpassword}}"
      name: "{{mysql_asteriskdb}}"
      state: import
      target: "{{path_crawlerinitandconfig}}/DBdumps/_AsteriskConf.sql"

  - name: Create database user
    mysql_user:
      login_host: "{{mysql_address}}"
      login_user: "{{mysql_rootuser}}"
      login_password: "{{mysql_rootpassword}}"
      host: "%"
      user: "{{mysql_user}}"
      password: "{{mysql_password}}"
      state: present
      priv: "{{mysql_dialerdb}}.*:ALL,GRANT/{{mysql_asteriskdb}}.*:ALL,GRANT"

